[package]
name = "osdp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = "0.16.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
serialport = "4.2.0"
