[package]
name = "osdp-cp"
version = "0.1.0"
edition = "2021"

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
osdp-sans.workspace = true
heapless.workspace = true
tokio = { version = "1.44.1", optional = true }
